import { getGrade, getGradeColor } from "./scoring";
import type { RoastResult } from "../types/roast";

export function exportRoastPDF(r: RoastResult): void {
  const w = window.open("", "_blank");
  if (!w) return;

  const cats = Object.keys(r.categories || {});
  const ch = cats
    .map((k) => {
      const c = r.categories[k];
      const bl = (c.bullets || [])
        .map(
          (b) =>
            `<li style="color:#666;font-size:13px;margin-bottom:4px">${escapeHtml(b)}</li>`
        )
        .join("");
      return `<div style="margin-bottom:20px;padding:20px;background:#f8f8f6;border-radius:12px">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px">
          <strong style="text-transform:uppercase">${escapeHtml(k)}</strong>
          <span style="font-size:28px;font-weight:900;color:${getGradeColor(getGrade(c.score))}">${c.score}</span>
        </div>
        <p style="color:#666;font-size:14px;line-height:1.6;margin-bottom:8px">${escapeHtml(c.roast)}</p>
        ${bl ? `<ul style="padding-left:20px;margin:0">${bl}</ul>` : ""}
      </div>`;
    })
    .join("");

  const rh = (r.recommendations || [])
    .slice(0, 3)
    .map(
      (x, i) =>
        `<div style="padding:14px 0;border-bottom:1px solid #eee">
          <strong>${i + 1}. ${escapeHtml(x.title)}</strong>
          <span style="font-size:11px;color:${x.priority === "critical" ? "#dc2626" : "#d97706"}">${x.priority}</span>
          <p style="color:#666;font-size:13px;margin-top:4px">${escapeHtml(x.description)}</p>
        </div>`
    )
    .join("");

  const grade = getGrade(r.overall_score);
  const color = getGradeColor(grade);

  w.document.write(`<!DOCTYPE html><html><head>
    <title>ROAST3D - ${escapeHtml(r.site_name)}</title>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Bebas+Neue&family=Chakra+Petch:wght@400;600;700&display=swap" rel="stylesheet">
    <style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Chakra Petch',sans-serif;color:#111;padding:48px;max-width:800px;margin:0 auto}@media print{body{padding:24px}}</style>
  </head><body>
    <div style="font-family:Permanent Marker;font-size:20px;background:linear-gradient(180deg,#ffd700,#ff4500,#8b0000);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:4px">ROAST3D</div>
    <div style="font-size:11px;color:#999;letter-spacing:2px;text-transform:uppercase;margin-bottom:4px">${escapeHtml(r.site_name)} &middot; ${escapeHtml(r.vibe)} energy</div>
    <div style="font-family:Permanent Marker;font-size:44px">ROAST REPORT</div>
    <div style="width:60px;height:4px;background:#FF3D00;margin:8px 0 32px"></div>
    <div style="display:flex;align-items:center;gap:32px;margin-bottom:32px;padding:24px;background:#f8f8f6;border-radius:16px">
      <div style="text-align:center;min-width:100px">
        <div style="font-family:Permanent Marker;font-size:64px;color:${color}">${grade}</div>
        <div style="font-size:14px;color:#999">${r.overall_score}/100</div>
      </div>
      <div>
        <div style="font-size:10px;color:#999;letter-spacing:2px;text-transform:uppercase;margin-bottom:4px">VERDICT</div>
        <div style="font-family:Permanent Marker;font-size:24px;color:${color}">${escapeHtml(r.verdict_name)}</div>
        <p style="color:#666;font-style:italic;margin-top:8px">"${escapeHtml(r.one_liner)}"</p>
      </div>
    </div>
    ${ch}
    <div style="margin:32px 0;padding:28px;background:#111;color:#fff;border-radius:16px">
      <div style="font-family:Bebas Neue;font-size:32px;color:#FF3D00;margin-bottom:12px">THE ONE THING THAT MATTERS</div>
      ${r.potential ? `<p style="color:rgba(255,255,255,.5);font-size:14px;margin-bottom:12px;line-height:1.6">${escapeHtml(r.potential)}</p>` : ""}
      <p style="font-size:16px;line-height:1.7;color:rgba(255,255,255,.9)">${escapeHtml(r.hot_take)}</p>
    </div>
    <div style="margin-bottom:24px">
      <div style="font-family:Permanent Marker;font-size:20px;margin-bottom:16px">TOP RECOMMENDATIONS</div>
      ${rh}
    </div>
    <div style="text-align:center;padding-top:24px;border-top:2px solid #eee;font-size:12px;color:#ccc">Generated by ROAST3D</div>
    <script>setTimeout(function(){window.print()},500)<\/script>
  </body></html>`);
  w.document.close();
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
